import {NSVBEntry} from "./nsvbLogic";

export const fakeDB: NSVBEntry [] & any = [
    {
        "id": "UCLA36",
        "age": "75 og derover",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": 0.05,
        "Std..Error": 0.25,
        "t.value": 0.2,
        "Pr...t..": 0.84,
        "antal ensomme i sample (>6 på UCLA)": 3,
        "i %": 4.69,
        "sample": 64,
        "% af samlet befolkning": 0.33,
        "Antal ensomme": 916,
        "pointLoss": "21.649.53 kr.",
        "pointGain": "19.840.923 kr."
    },
    {
        "id": "UCLA38",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": 0.01,
        "Std..Error": 0.86,
        "t.value": 0.01,
        "Pr...t..": 0.99,
        "antal ensomme i sample (>6 på UCLA)": 0,
        "i %": 0,
        "sample": 15,
        "% af samlet befolkning": 0.08,
        "Antal ensomme": 0,
        "pointLoss": "3.936.16 kr.",
        "pointGain": "0 kr."
    },
    {
        "id": "UCLA58",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.25,
        "Std..Error": 0.14,
        "t.value": -1.8,
        "Pr...t..": 0.09,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 5,
        "sample": 20,
        "% af samlet befolkning": 0.1,
        "Antal ensomme": 305,
        "pointLoss": "33.880.08 kr.",
        "pointGain": "10.349.909 kr."
    },
    {
        "id": "UCLA61",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.78,
        "Std..Error": 0.08,
        "t.value": -9.84,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 32,
        "i %": 8.25,
        "sample": 388,
        "% af samlet befolkning": 2.03,
        "Antal ensomme": 9776,
        "pointLoss": "123.762.15 kr.",
        "pointGain": "1.209.845.605 kr."
    },
    {
        "id": "UCLA144",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.32,
        "Std..Error": 0.21,
        "t.value": -1.5,
        "Pr...t..": 0.14,
        "antal ensomme i sample (>6 på UCLA)": 3,
        "i %": 4.48,
        "sample": 67,
        "% af samlet befolkning": 0.35,
        "Antal ensomme": 916,
        "pointLoss": "44.632.59 kr.",
        "pointGain": "40.903.966 kr."
    },
    {
        "id": "UCLA74",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.35,
        "Std..Error": 0.35,
        "t.value": -0.99,
        "Pr...t..": 0.33,
        "antal ensomme i sample (>6 på UCLA)": 3,
        "i %": 10.34,
        "sample": 29,
        "% af samlet befolkning": 0.15,
        "Antal ensomme": 916,
        "pointLoss": "49.728.42 kr.",
        "pointGain": "45.574.096 kr."
    },
    {
        "id": "UCLA135",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.75,
        "Std..Error": 0.12,
        "t.value": -6.31,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 7,
        "i %": 6.25,
        "sample": 112,
        "% af samlet befolkning": 0.59,
        "Antal ensomme": 2138,
        "pointLoss": "118.901.78 kr.",
        "pointGain": "254.260.276 kr."
    },
    {
        "id": "UCLA85",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.75,
        "Std..Error": 0.09,
        "t.value": -8.13,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 18,
        "i %": 6.67,
        "sample": 270,
        "% af samlet befolkning": 1.41,
        "Antal ensomme": 5499,
        "pointLoss": "118.238.34 kr.",
        "pointGain": "650.164.055 kr."
    },
    {
        "id": "UCLA8",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.41,
        "Std..Error": 0.18,
        "t.value": -2.27,
        "Pr...t..": 0.03,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 10,
        "sample": 50,
        "% af samlet befolkning": 0.26,
        "Antal ensomme": 1527,
        "pointLoss": "58.589.28 kr.",
        "pointGain": "89.491.187 kr."
    },
    {
        "id": "UCLA134",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.74,
        "Std..Error": 0.09,
        "t.value": -8.57,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 20,
        "i %": 8.44,
        "sample": 237,
        "% af samlet befolkning": 1.24,
        "Antal ensomme": 6110,
        "pointLoss": "115.944.88 kr.",
        "pointGain": "708.392.082 kr."
    },
    {
        "id": "UCLA11",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.7,
        "Std..Error": 0.09,
        "t.value": -7.7,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 18,
        "i %": 15,
        "sample": 120,
        "% af samlet befolkning": 0.63,
        "Antal ensomme": 5499,
        "pointLoss": "109.197.48 kr.",
        "pointGain": "600.450.531 kr."
    },
    {
        "id": "UCLA96",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.7,
        "Std..Error": 0.09,
        "t.value": -7.68,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 16,
        "i %": 7.05,
        "sample": 227,
        "% af samlet befolkning": 1.19,
        "Antal ensomme": 4888,
        "pointLoss": "109.192.59 kr.",
        "pointGain": "533.709.922 kr."
    },
    {
        "id": "UCLA29",
        "age": "75 og derover",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.44,
        "Std..Error": 0.19,
        "t.value": -2.28,
        "Pr...t..": 0.03,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 5.71,
        "sample": 35,
        "% af samlet befolkning": 0.18,
        "Antal ensomme": 611,
        "pointLoss": "63.242.25 kr.",
        "pointGain": "38.639.317 kr."
    },
    {
        "id": "UCLA15",
        "age": "16 to 24",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.44,
        "Std..Error": 0.13,
        "t.value": -3.49,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 11,
        "i %": 10.19,
        "sample": 108,
        "% af samlet befolkning": 0.56,
        "Antal ensomme": 3360,
        "pointLoss": "63.605.40 kr.",
        "pointGain": "213.736.547 kr."
    },
    {
        "id": "UCLA105",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.44,
        "Std..Error": 0.1,
        "t.value": -4.3,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 15,
        "i %": 6.1,
        "sample": 246,
        "% af samlet befolkning": 1.29,
        "Antal ensomme": 4582,
        "pointLoss": "63.619.07 kr.",
        "pointGain": "291.521.555 kr."
    },
    {
        "id": "UCLA35",
        "age": "75 og derover",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.44,
        "Std..Error": 0.14,
        "t.value": -3.06,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 6.59,
        "sample": 91,
        "% af samlet befolkning": 0.48,
        "Antal ensomme": 1833,
        "pointLoss": "63.835.06 kr.",
        "pointGain": "117.004.526 kr."
    },
    {
        "id": "UCLA86",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.7,
        "Std..Error": 0.05,
        "t.value": -12.72,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 36,
        "i %": 4.81,
        "sample": 749,
        "% af samlet befolkning": 3.92,
        "Antal ensomme": 10998,
        "pointLoss": "108.456.02 kr.",
        "pointGain": "1.192.746.833 kr."
    },
    {
        "id": "UCLA23",
        "age": "75 og derover",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.45,
        "Std..Error": 0.2,
        "t.value": -2.19,
        "Pr...t..": 0.03,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 7.14,
        "sample": 56,
        "% af samlet befolkning": 0.29,
        "Antal ensomme": 1222,
        "pointLoss": "64.881.57 kr.",
        "pointGain": "79.281.790 kr."
    },
    {
        "id": "UCLA129",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.45,
        "Std..Error": 0.08,
        "t.value": -5.34,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 18,
        "i %": 6.77,
        "sample": 266,
        "% af samlet befolkning": 1.39,
        "Antal ensomme": 5499,
        "pointLoss": "64.917.98 kr.",
        "pointGain": "356.968.255 kr."
    },
    {
        "id": "UCLA110",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.68,
        "Std..Error": 0.07,
        "t.value": -10.01,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 22,
        "i %": 4.95,
        "sample": 444,
        "% af samlet befolkning": 2.32,
        "Antal ensomme": 6721,
        "pointLoss": "105.684.41 kr.",
        "pointGain": "710.273.654 kr."
    },
    {
        "id": "UCLA93",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.67,
        "Std..Error": 0.11,
        "t.value": -5.89,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 25,
        "i %": 12.5,
        "sample": 200,
        "% af samlet befolkning": 1.05,
        "Antal ensomme": 7637,
        "pointLoss": "102.324.87 kr.",
        "pointGain": "781.471.790 kr."
    },
    {
        "id": "UCLA54",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.46,
        "Std..Error": 0.04,
        "t.value": -10.44,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 42,
        "i %": 2.7,
        "sample": 1554,
        "% af samlet befolkning": 8.12,
        "Antal ensomme": 12830,
        "pointLoss": "67.452.07 kr.",
        "pointGain": "865.439.483 kr."
    },
    {
        "id": "UCLA119",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.07,
        "t.value": -10.03,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 18,
        "i %": 3.94,
        "sample": 457,
        "% af samlet befolkning": 2.39,
        "Antal ensomme": 5499,
        "pointLoss": "101.253.57 kr.",
        "pointGain": "556.768.872 kr."
    },
    {
        "id": "UCLA16",
        "age": "16 to 24",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.46,
        "Std..Error": 0.15,
        "t.value": -3.13,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 15,
        "sample": 40,
        "% af samlet befolkning": 0.21,
        "Antal ensomme": 1833,
        "pointLoss": "67.752.37 kr.",
        "pointGain": "124.184.635 kr."
    },
    {
        "id": "UCLA152",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.47,
        "Std..Error": 0.14,
        "t.value": -3.38,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 3.28,
        "sample": 122,
        "% af samlet befolkning": 0.64,
        "Antal ensomme": 1222,
        "pointLoss": "68.258.98 kr.",
        "pointGain": "83.408.807 kr."
    },
    {
        "id": "UCLA79",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.47,
        "Std..Error": 0.05,
        "t.value": -8.58,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 37,
        "i %": 4.38,
        "sample": 844,
        "% af samlet befolkning": 4.41,
        "Antal ensomme": 11303,
        "pointLoss": "68.472.20 kr.",
        "pointGain": "773.941.451 kr."
    },
    {
        "id": "UCLA21",
        "age": "75 og derover",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.08,
        "t.value": -8.06,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 14,
        "i %": 3.7,
        "sample": 378,
        "% af samlet befolkning": 1.98,
        "Antal ensomme": 4277,
        "pointLoss": "100.690.49 kr.",
        "pointGain": "430.634.292 kr."
    },
    {
        "id": "UCLA114",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.47,
        "Std..Error": 0.29,
        "t.value": -1.63,
        "Pr...t..": 0.12,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 8.7,
        "sample": 23,
        "% af samlet befolkning": 0.12,
        "Antal ensomme": 611,
        "pointLoss": "68.711.62 kr.",
        "pointGain": "41.980.951 kr."
    },
    {
        "id": "UCLA31",
        "age": "75 og derover",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.47,
        "Std..Error": 0.21,
        "t.value": -2.25,
        "Pr...t..": 0.04,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 11.76,
        "sample": 17,
        "% af samlet befolkning": 0.09,
        "Antal ensomme": 611,
        "pointLoss": "69.192.75 kr.",
        "pointGain": "42.274.909 kr."
    },
    {
        "id": "UCLA27",
        "age": "75 og derover",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.65,
        "Std..Error": 0.08,
        "t.value": -7.65,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 16,
        "i %": 5.78,
        "sample": 277,
        "% af samlet befolkning": 1.45,
        "Antal ensomme": 4888,
        "pointLoss": "98.879.13 kr.",
        "pointGain": "483.299.929 kr."
    },
    {
        "id": "UCLA2",
        "age": "16 to 24",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.48,
        "Std..Error": 0.18,
        "t.value": -2.66,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 10.34,
        "sample": 58,
        "% af samlet befolkning": 0.3,
        "Antal ensomme": 1833,
        "pointLoss": "69.487.50 kr.",
        "pointGain": "127.364.981 kr."
    },
    {
        "id": "UCLA53",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.48,
        "Std..Error": 0.06,
        "t.value": -8.19,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 39,
        "i %": 4.36,
        "sample": 894,
        "% af samlet befolkning": 4.67,
        "Antal ensomme": 11914,
        "pointLoss": "69.820.75 kr.",
        "pointGain": "831.842.753 kr."
    },
    {
        "id": "UCLA56",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.48,
        "Std..Error": 0.11,
        "t.value": -4.26,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 7,
        "i %": 2.78,
        "sample": 252,
        "% af samlet befolkning": 1.32,
        "Antal ensomme": 2138,
        "pointLoss": "69.897.67 kr.",
        "pointGain": "149.469.587 kr."
    },
    {
        "id": "UCLA88",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.64,
        "Std..Error": 0.12,
        "t.value": -5.5,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 3.28,
        "sample": 183,
        "% af samlet befolkning": 0.96,
        "Antal ensomme": 1833,
        "pointLoss": "97.169.49 kr.",
        "pointGain": "178.103.849 kr."
    },
    {
        "id": "UCLA75",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.49,
        "Std..Error": 0.03,
        "t.value": -14.33,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 118,
        "i %": 5.59,
        "sample": 2111,
        "% af samlet befolkning": 11.04,
        "Antal ensomme": 36047,
        "pointLoss": "71.377.67 kr.",
        "pointGain": "2.572.980.473 kr."
    },
    {
        "id": "UCLA34",
        "age": "75 og derover",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.49,
        "Std..Error": 0.08,
        "t.value": -5.93,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 8,
        "i %": 2.66,
        "sample": 301,
        "% af samlet befolkning": 1.57,
        "Antal ensomme": 2444,
        "pointLoss": "71.468.12 kr.",
        "pointGain": "174.660.404 kr."
    },
    {
        "id": "UCLA161",
        "age": "All",
        "sex": "Mand",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.49,
        "Std..Error": 0.06,
        "t.value": -8.22,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 41,
        "i %": 5.99,
        "sample": 685,
        "% af samlet befolkning": 3.58,
        "Antal ensomme": 12525,
        "pointLoss": "71.788.46 kr.",
        "pointGain": "899.146.793 kr."
    },
    {
        "id": "UCLA177",
        "age": "All",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.49,
        "Std..Error": 0.04,
        "t.value": -11.02,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 58,
        "i %": 4.89,
        "sample": 1186,
        "% af samlet befolkning": 6.2,
        "Antal ensomme": 17718,
        "pointLoss": "72.655.68 kr.",
        "pointGain": "1.287.329.354 kr."
    },
    {
        "id": "UCLA51",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.49,
        "Std..Error": 0.04,
        "t.value": -12.75,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 56,
        "i %": 3.03,
        "sample": 1847,
        "% af samlet befolkning": 9.66,
        "Antal ensomme": 17107,
        "pointLoss": "72.698.36 kr.",
        "pointGain": "1.243.668.922 kr."
    },
    {
        "id": "UCLA59",
        "age": "65 to 74",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.5,
        "Std..Error": 0.03,
        "t.value": -16.97,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 116,
        "i %": 3.11,
        "sample": 3735,
        "% af samlet befolkning": 19.53,
        "Antal ensomme": 35436,
        "pointLoss": "73.153.94 kr.",
        "pointGain": "2.592.315.404 kr."
    },
    {
        "id": "UCLA64",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.11,
        "t.value": -5.5,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 9,
        "i %": 5.36,
        "sample": 168,
        "% af samlet befolkning": 0.88,
        "Antal ensomme": 2749,
        "pointLoss": "94.792.64 kr.",
        "pointGain": "260.620.906 kr."
    },
    {
        "id": "UCLA169",
        "age": "All",
        "sex": "Kvinde",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.5,
        "Std..Error": 0.07,
        "t.value": -7.33,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 17,
        "i %": 3.39,
        "sample": 501,
        "% af samlet befolkning": 2.62,
        "Antal ensomme": 5193,
        "pointLoss": "73.752.22 kr.",
        "pointGain": "383.015.302 kr."
    },
    {
        "id": "UCLA95",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.61,
        "Std..Error": 0.06,
        "t.value": -9.47,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 24,
        "i %": 4.46,
        "sample": 538,
        "% af samlet befolkning": 2.81,
        "Antal ensomme": 7332,
        "pointLoss": "91.848.65 kr.",
        "pointGain": "673.404.695 kr."
    },
    {
        "id": "UCLA109",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.61,
        "Std..Error": 0.11,
        "t.value": -5.69,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 23,
        "i %": 20.18,
        "sample": 114,
        "% af samlet befolkning": 0.6,
        "Antal ensomme": 7026,
        "pointLoss": "91.587.54 kr.",
        "pointGain": "643.511.542 kr."
    },
    {
        "id": "UCLA78",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.51,
        "Std..Error": 0.04,
        "t.value": -12.91,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 75,
        "i %": 4.38,
        "sample": 1713,
        "% af samlet befolkning": 8.96,
        "Antal ensomme": 22911,
        "pointLoss": "75.277.52 kr.",
        "pointGain": "1.724.720.298 kr."
    },
    {
        "id": "UCLA44",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.51,
        "Std..Error": 0.04,
        "t.value": -11.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 60,
        "i %": 3.18,
        "sample": 1888,
        "% af samlet befolkning": 9.87,
        "Antal ensomme": 18329,
        "pointLoss": "75.319.22 kr.",
        "pointGain": "1.380.540.559 kr."
    },
    {
        "id": "UCLA62",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.06,
        "t.value": -10.64,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 32,
        "i %": 3.54,
        "sample": 903,
        "% af samlet befolkning": 4.72,
        "Antal ensomme": 9776,
        "pointLoss": "91.254.53 kr.",
        "pointGain": "892.065.090 kr."
    },
    {
        "id": "UCLA72",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.1,
        "t.value": -6.23,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 14,
        "i %": 6.19,
        "sample": 226,
        "% af samlet befolkning": 1.18,
        "Antal ensomme": 4277,
        "pointLoss": "90.790.81 kr.",
        "pointGain": "388.295.201 kr."
    },
    {
        "id": "UCLA32",
        "age": "75 og derover",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.52,
        "Std..Error": 0.06,
        "t.value": -9.42,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 57,
        "i %": 7.93,
        "sample": 719,
        "% af samlet befolkning": 3.76,
        "Antal ensomme": 17413,
        "pointLoss": "76.793.19 kr.",
        "pointGain": "1.337.179.334 kr."
    },
    {
        "id": "UCLA148",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.52,
        "Std..Error": 0.06,
        "t.value": -8.2,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 48,
        "i %": 13.91,
        "sample": 345,
        "% af samlet befolkning": 1.8,
        "Antal ensomme": 14663,
        "pointLoss": "77.424.88 kr.",
        "pointGain": "1.135.308.475 kr."
    },
    {
        "id": "UCLA25",
        "age": "75 og derover",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.53,
        "Std..Error": 0.05,
        "t.value": -10,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 44,
        "i %": 4.97,
        "sample": 885,
        "% af samlet befolkning": 4.63,
        "Antal ensomme": 13441,
        "pointLoss": "78.391.26 kr.",
        "pointGain": "1.053.688.979 kr."
    },
    {
        "id": "UCLA22",
        "age": "75 og derover",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.11,
        "t.value": -5.31,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 4.51,
        "sample": 133,
        "% af samlet befolkning": 0.7,
        "Antal ensomme": 1833,
        "pointLoss": "90.401.03 kr.",
        "pointGain": "165.697.792 kr."
    },
    {
        "id": "UCLA37",
        "age": "75 og derover",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.53,
        "Std..Error": 0.03,
        "t.value": -15.37,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 106,
        "i %": 5.72,
        "sample": 1852,
        "% af samlet befolkning": 9.68,
        "Antal ensomme": 32382,
        "pointLoss": "78.865.70 kr.",
        "pointGain": "2.553.795.485 kr."
    },
    {
        "id": "UCLA48",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.59,
        "Std..Error": 0.09,
        "t.value": -6.55,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 13,
        "i %": 2.95,
        "sample": 440,
        "% af samlet befolkning": 2.3,
        "Antal ensomme": 3971,
        "pointLoss": "89.732.49 kr.",
        "pointGain": "356.356.893 kr."
    },
    {
        "id": "UCLA30",
        "age": "75 og derover",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.54,
        "Std..Error": 0.05,
        "t.value": -11.72,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 62,
        "i %": 6.41,
        "sample": 967,
        "% af samlet befolkning": 5.06,
        "Antal ensomme": 18940,
        "pointLoss": "80.146.35 kr.",
        "pointGain": "1.517.985.299 kr."
    },
    {
        "id": "UCLA87",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.59,
        "Std..Error": 0.09,
        "t.value": -6.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 16,
        "i %": 7.02,
        "sample": 228,
        "% af samlet befolkning": 1.19,
        "Antal ensomme": 4888,
        "pointLoss": "88.176.90 kr.",
        "pointGain": "430.989.712 kr."
    },
    {
        "id": "UCLA82",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.21,
        "t.value": -2.6,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 6.78,
        "sample": 59,
        "% af samlet befolkning": 0.31,
        "Antal ensomme": 1222,
        "pointLoss": "82.082.54 kr.",
        "pointGain": "100.300.447 kr."
    },
    {
        "id": "UCLA130",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.16,
        "t.value": -3.44,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 12,
        "sample": 50,
        "% af samlet befolkning": 0.26,
        "Antal ensomme": 1833,
        "pointLoss": "82.238.32 kr.",
        "pointGain": "150.736.208 kr."
    },
    {
        "id": "UCLA132",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.1,
        "t.value": -5.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 18,
        "i %": 13.33,
        "sample": 135,
        "% af samlet befolkning": 0.71,
        "Antal ensomme": 5499,
        "pointLoss": "87.695.71 kr.",
        "pointGain": "482.217.485 kr."
    },
    {
        "id": "UCLA83",
        "age": "55 to 64",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.02,
        "t.value": -22.25,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 208,
        "i %": 5.19,
        "sample": 4004,
        "% af samlet befolkning": 20.93,
        "Antal ensomme": 63541,
        "pointLoss": "82.478.81 kr.",
        "pointGain": "5.240.803.149 kr."
    },
    {
        "id": "UCLA94",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.05,
        "t.value": -11.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 46,
        "i %": 5.83,
        "sample": 789,
        "% af samlet befolkning": 4.12,
        "Antal ensomme": 14052,
        "pointLoss": "87.538.92 kr.",
        "pointGain": "1.230.130.355 kr."
    },
    {
        "id": "UCLA166",
        "age": "All",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.02,
        "t.value": -22.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 198,
        "i %": 5.95,
        "sample": 3325,
        "% af samlet befolkning": 17.38,
        "Antal ensomme": 60486,
        "pointLoss": "82.811.13 kr.",
        "pointGain": "5.008.942.157 kr."
    },
    {
        "id": "UCLA164",
        "age": "All",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.03,
        "t.value": -16.65,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 183,
        "i %": 15.25,
        "sample": 1200,
        "% af samlet befolkning": 6.27,
        "Antal ensomme": 55904,
        "pointLoss": "82.833.84 kr.",
        "pointGain": "4.630.746.511 kr."
    },
    {
        "id": "UCLA142",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.07,
        "t.value": -8.08,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 38,
        "i %": 14.84,
        "sample": 256,
        "% af samlet befolkning": 1.34,
        "Antal ensomme": 11608,
        "pointLoss": "86.960.62 kr.",
        "pointGain": "1.009.481.464 kr."
    },
    {
        "id": "UCLA143",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.07,
        "t.value": -8.76,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 19,
        "i %": 6.29,
        "sample": 302,
        "% af samlet befolkning": 1.58,
        "Antal ensomme": 5804,
        "pointLoss": "85.437.00 kr.",
        "pointGain": "495.897.260 kr."
    },
    {
        "id": "UCLA124",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.1,
        "t.value": -5.45,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 21,
        "i %": 12.96,
        "sample": 162,
        "% af samlet befolkning": 0.85,
        "Antal ensomme": 6415,
        "pointLoss": "83.655.76 kr.",
        "pointGain": "536.669.945 kr."
    },
    {
        "id": "UCLA41",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.12,
        "t.value": -4.91,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 1.87,
        "sample": 321,
        "% af samlet befolkning": 1.68,
        "Antal ensomme": 1833,
        "pointLoss": "84.871.83 kr.",
        "pointGain": "155.563.215 kr."
    },
    {
        "id": "UCLA167",
        "age": "All",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.03,
        "t.value": -18.6,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 108,
        "i %": 4.27,
        "sample": 2532,
        "% af samlet befolkning": 13.24,
        "Antal ensomme": 32993,
        "pointLoss": "83.968.74 kr.",
        "pointGain": "2.770.342.786 kr."
    },
    {
        "id": "UCLA113",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.12,
        "t.value": -4.77,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 12,
        "i %": 8.63,
        "sample": 139,
        "% af samlet befolkning": 0.73,
        "Antal ensomme": 3666,
        "pointLoss": "83.974.55 kr.",
        "pointGain": "307.837.155 kr."
    },
    {
        "id": "UCLA175",
        "age": "All",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.02,
        "t.value": -22.62,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 161,
        "i %": 4.27,
        "sample": 3769,
        "% af samlet befolkning": 19.7,
        "Antal ensomme": 49183,
        "pointLoss": "84.153.72 kr.",
        "pointGain": "4.138.960.591 kr."
    },
    {
        "id": "UCLA128",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.12,
        "t.value": -4.89,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 10,
        "i %": 5.03,
        "sample": 199,
        "% af samlet befolkning": 1.04,
        "Antal ensomme": 3055,
        "pointLoss": "84.222.37 kr.",
        "pointGain": "257.288.033 kr."
    },
    {
        "id": "UCLA159",
        "age": "All",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.04,
        "t.value": -12.88,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 53,
        "i %": 4.28,
        "sample": 1237,
        "% af samlet befolkning": 6.47,
        "Antal ensomme": 16191,
        "pointLoss": "84.752.27 kr.",
        "pointGain": "1.372.206.075 kr."
    },
    {
        "id": "UCLA118",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.06,
        "t.value": -9.25,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 28,
        "i %": 6.48,
        "sample": 432,
        "% af samlet befolkning": 2.26,
        "Antal ensomme": 8554,
        "pointLoss": "83.705.62 kr.",
        "pointGain": "715.986.346 kr."
    },
    {
        "id": "UCLA13",
        "age": "16 to 24",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.03,
        "t.value": -17.82,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 174,
        "i %": 13.05,
        "sample": 1333,
        "% af samlet befolkning": 6.97,
        "Antal ensomme": 53155,
        "pointLoss": "85.187.32 kr.",
        "pointGain": "4.528.103.458 kr."
    },
    {
        "id": "UCLA138",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.23,
        "t.value": -2.46,
        "Pr...t..": 0.02,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 27.27,
        "sample": 22,
        "% af samlet befolkning": 0.12,
        "Antal ensomme": 1833,
        "pointLoss": "85.385.87 kr.",
        "pointGain": "156.505.412 kr."
    },
    {
        "id": "UCLA6",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.04,
        "t.value": -13.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 122,
        "i %": 16.07,
        "sample": 759,
        "% af samlet befolkning": 3.97,
        "Antal ensomme": 37269,
        "pointLoss": "83.343.59 kr.",
        "pointGain": "3.106.162.146 kr."
    },
    {
        "id": "UCLA5",
        "age": "16 to 24",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.04,
        "t.value": -12.9,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 78,
        "i %": 10.06,
        "sample": 775,
        "% af samlet befolkning": 4.05,
        "Antal ensomme": 23828,
        "pointLoss": "85.755.74 kr.",
        "pointGain": "2.043.383.682 kr."
    },
    {
        "id": "UCLA172",
        "age": "All",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.03,
        "t.value": -21.88,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 267,
        "i %": 12.99,
        "sample": 2056,
        "% af samlet befolkning": 10.75,
        "Antal ensomme": 81565,
        "pointLoss": "85.779.80 kr.",
        "pointGain": "6.996.622.004 kr."
    },
    {
        "id": "UCLA122",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.19,
        "t.value": -3.05,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 14.81,
        "sample": 27,
        "% af samlet befolkning": 0.14,
        "Antal ensomme": 1222,
        "pointLoss": "85.884.57 kr.",
        "pointGain": "104.946.332 kr."
    },
    {
        "id": "UCLA153",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.1,
        "t.value": -5.64,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 9,
        "i %": 5.17,
        "sample": 174,
        "% af samlet befolkning": 0.91,
        "Antal ensomme": 2749,
        "pointLoss": "86.000.26 kr.",
        "pointGain": "236.447.319 kr."
    },
    {
        "id": "UCLA81",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.57,
        "Std..Error": 0.11,
        "t.value": -5.39,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 2.96,
        "sample": 203,
        "% af samlet befolkning": 1.06,
        "Antal ensomme": 1833,
        "pointLoss": "86.042.76 kr.",
        "pointGain": "157.709.443 kr."
    },
    {
        "id": "UCLA145",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.56,
        "Std..Error": 0.13,
        "t.value": -4.15,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 3.88,
        "sample": 103,
        "% af samlet befolkning": 0.54,
        "Antal ensomme": 1222,
        "pointLoss": "83.243.50 kr.",
        "pointGain": "101.719.079 kr."
    },
    {
        "id": "UCLA55",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.07,
        "t.value": -8.14,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 19,
        "i %": 2.5,
        "sample": 761,
        "% af samlet befolkning": 3.98,
        "Antal ensomme": 5804,
        "pointLoss": "87.353.05 kr.",
        "pointGain": "507.018.482 kr."
    },
    {
        "id": "UCLA147",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.04,
        "t.value": -15.55,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 109,
        "i %": 10.71,
        "sample": 1018,
        "% af samlet befolkning": 5.32,
        "Antal ensomme": 33298,
        "pointLoss": "87.426.06 kr.",
        "pointGain": "2.911.116.189 kr."
    },
    {
        "id": "UCLA",
        "age": "16 to 24",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.05,
        "t.value": -10.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 52,
        "i %": 9.06,
        "sample": 574,
        "% af samlet befolkning": 3,
        "Antal ensomme": 15885,
        "pointLoss": "82.525.52 kr.",
        "pointGain": "1.310.942.767 kr."
    },
    {
        "id": "UCLA39",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.55,
        "Std..Error": 0.09,
        "t.value": -6.02,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 22,
        "i %": 5.57,
        "sample": 395,
        "% af samlet befolkning": 2.07,
        "Antal ensomme": 6721,
        "pointLoss": "82.309.40 kr.",
        "pointGain": "553.177.173 kr."
    },
    {
        "id": "UCLA171",
        "age": "All",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.01,
        "t.value": -42.7,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 735,
        "i %": 7.12,
        "sample": 10320,
        "% af samlet befolkning": 53.95,
        "Antal ensomme": 224533,
        "pointLoss": "87.811.81 kr.",
        "pointGain": "19.716.617.299 kr."
    },
    {
        "id": "UCLA9",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.58,
        "Std..Error": 0.19,
        "t.value": -3.08,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 13.33,
        "sample": 30,
        "% af samlet befolkning": 0.16,
        "Antal ensomme": 1222,
        "pointLoss": "87.935.35 kr.",
        "pointGain": "107.452.273 kr."
    },
    {
        "id": "UCLA168",
        "age": "All",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.59,
        "Std..Error": 0.05,
        "t.value": -11.08,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 44,
        "i %": 5.61,
        "sample": 785,
        "% af samlet befolkning": 4.1,
        "Antal ensomme": 13441,
        "pointLoss": "88.029.14 kr.",
        "pointGain": "1.183.235.650 kr."
    },
    {
        "id": "UCLA123",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.59,
        "Std..Error": 0.03,
        "t.value": -16.78,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 93,
        "i %": 6.88,
        "sample": 1352,
        "% af samlet befolkning": 7.07,
        "Antal ensomme": 28410,
        "pointLoss": "88.109.44 kr.",
        "pointGain": "2.503.211.363 kr."
    },
    {
        "id": "UCLA42",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.54,
        "Std..Error": 0.15,
        "t.value": -3.71,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 3.57,
        "sample": 140,
        "% af samlet befolkning": 0.73,
        "Antal ensomme": 1527,
        "pointLoss": "80.205.71 kr.",
        "pointGain": "122.508.839 kr."
    },
    {
        "id": "UCLA4",
        "age": "16 to 24",
        "sex": "Mand",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.59,
        "Std..Error": 0.17,
        "t.value": -3.44,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 7,
        "i %": 10.94,
        "sample": 64,
        "% af samlet befolkning": 0.33,
        "Antal ensomme": 2138,
        "pointLoss": "88.729.04 kr.",
        "pointGain": "189.738.706 kr."
    },
    {
        "id": "UCLA26",
        "age": "75 og derover",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.54,
        "Std..Error": 0.07,
        "t.value": -8.09,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 40,
        "i %": 8.51,
        "sample": 470,
        "% af samlet befolkning": 2.46,
        "Antal ensomme": 12219,
        "pointLoss": "79.496.87 kr.",
        "pointGain": "971.409.001 kr."
    },
    {
        "id": "UCLA156",
        "age": "All",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.04,
        "t.value": -13.87,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 84,
        "i %": 9.81,
        "sample": 856,
        "% af samlet befolkning": 4.48,
        "Antal ensomme": 25661,
        "pointLoss": "89.905.89 kr.",
        "pointGain": "2.307.063.561 kr."
    },
    {
        "id": "UCLA137",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.16,
        "t.value": -3.78,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 7.04,
        "sample": 71,
        "% af samlet befolkning": 0.37,
        "Antal ensomme": 1527,
        "pointLoss": "89.960.47 kr.",
        "pointGain": "137.408.572 kr."
    },
    {
        "id": "UCLA19",
        "age": "16 to 24",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.03,
        "t.value": -22.14,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 244,
        "i %": 13.62,
        "sample": 1791,
        "% af samlet befolkning": 9.36,
        "Antal ensomme": 74539,
        "pointLoss": "90.373.39 kr.",
        "pointGain": "6.736.316.731 kr."
    },
    {
        "id": "UCLA65",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.53,
        "Std..Error": 0.13,
        "t.value": -4.24,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 3.76,
        "sample": 133,
        "% af samlet befolkning": 0.7,
        "Antal ensomme": 1527,
        "pointLoss": "78.686.19 kr.",
        "pointGain": "120.187.862 kr."
    },
    {
        "id": "UCLA174",
        "age": "All",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.02,
        "t.value": -33,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 348,
        "i %": 5.02,
        "sample": 6937,
        "% af samlet befolkning": 36.27,
        "Antal ensomme": 106309,
        "pointLoss": "90.558.67 kr.",
        "pointGain": "9.627.230.858 kr."
    },
    {
        "id": "UCLA103",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.05,
        "t.value": -11.49,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 40,
        "i %": 5.22,
        "sample": 766,
        "% af samlet befolkning": 4,
        "Antal ensomme": 12219,
        "pointLoss": "90.581.59 kr.",
        "pointGain": "1.106.858.372 kr."
    },
    {
        "id": "UCLA69",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.52,
        "Std..Error": 0.08,
        "t.value": -6.48,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 26,
        "i %": 7.37,
        "sample": 353,
        "% af samlet befolkning": 1.85,
        "Antal ensomme": 7943,
        "pointLoss": "76.255.47 kr.",
        "pointGain": "605.670.583 kr."
    },
    {
        "id": "UCLA12",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.03,
        "t.value": -17.47,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 166,
        "i %": 16.34,
        "sample": 1016,
        "% af samlet befolkning": 5.31,
        "Antal ensomme": 50711,
        "pointLoss": "90.857.25 kr.",
        "pointGain": "4.607.441.288 kr."
    },
    {
        "id": "UCLA92",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.11,
        "t.value": -5.25,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 9,
        "i %": 11.54,
        "sample": 78,
        "% af samlet befolkning": 0.41,
        "Antal ensomme": 2749,
        "pointLoss": "90.984.64 kr.",
        "pointGain": "250.151.268 kr."
    },
    {
        "id": "UCLA176",
        "age": "All",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.04,
        "t.value": -15.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 75,
        "i %": 5.02,
        "sample": 1494,
        "% af samlet befolkning": 7.81,
        "Antal ensomme": 22911,
        "pointLoss": "91.040.04 kr.",
        "pointGain": "2.085.863.116 kr."
    },
    {
        "id": "UCLA179",
        "age": "All",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.6,
        "Std..Error": 0.01,
        "t.value": -58.03,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 1244,
        "i %": 6.5,
        "sample": 19128,
        "% af samlet befolkning": 100,
        "Antal ensomme": 380025,
        "pointLoss": "91.146.71 kr.",
        "pointGain": "34.638.054.724 kr."
    },
    {
        "id": "UCLA63",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.52,
        "Std..Error": 0.1,
        "t.value": -5.41,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 9,
        "i %": 3.64,
        "sample": 247,
        "% af samlet befolkning": 1.29,
        "Antal ensomme": 2749,
        "pointLoss": "76.223.65 kr.",
        "pointGain": "209.567.703 kr."
    },
    {
        "id": "UCLA120",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.51,
        "Std..Error": 0.15,
        "t.value": -3.45,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 5.61,
        "sample": 107,
        "% af samlet befolkning": 0.56,
        "Antal ensomme": 1833,
        "pointLoss": "75.224.65 kr.",
        "pointGain": "137.880.722 kr."
    },
    {
        "id": "UCLA140",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.5,
        "Std..Error": 0.08,
        "t.value": -6.22,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 30,
        "i %": 14.29,
        "sample": 210,
        "% af samlet befolkning": 1.1,
        "Antal ensomme": 9165,
        "pointLoss": "74.170.28 kr.",
        "pointGain": "679.740.734 kr."
    },
    {
        "id": "UCLA131",
        "age": "35 to 44",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.61,
        "Std..Error": 0.03,
        "t.value": -22.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 168,
        "i %": 6.98,
        "sample": 2406,
        "% af samlet befolkning": 12.58,
        "Antal ensomme": 51322,
        "pointLoss": "92.191.76 kr.",
        "pointGain": "4.731.441.953 kr."
    },
    {
        "id": "UCLA127",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.61,
        "Std..Error": 0.06,
        "t.value": -10.46,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 25,
        "i %": 3.89,
        "sample": 643,
        "% af samlet befolkning": 3.36,
        "Antal ensomme": 7637,
        "pointLoss": "92.392.29 kr.",
        "pointGain": "705.615.109 kr."
    },
    {
        "id": "UCLA80",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.61,
        "Std..Error": 0.07,
        "t.value": -8.36,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 23,
        "i %": 5.84,
        "sample": 394,
        "% af samlet befolkning": 2.06,
        "Antal ensomme": 7026,
        "pointLoss": "92.616.31 kr.",
        "pointGain": "650.739.847 kr."
    },
    {
        "id": "UCLA126",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.05,
        "t.value": -13.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 50,
        "i %": 5.71,
        "sample": 876,
        "% af samlet befolkning": 4.58,
        "Antal ensomme": 15274,
        "pointLoss": "93.296.42 kr.",
        "pointGain": "1.425.040.083 kr."
    },
    {
        "id": "UCLA99",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "All",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.03,
        "t.value": -19.14,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 131,
        "i %": 6.52,
        "sample": 2009,
        "% af samlet befolkning": 10.5,
        "Antal ensomme": 40019,
        "pointLoss": "93.348.44 kr.",
        "pointGain": "3.735.687.076 kr."
    },
    {
        "id": "UCLA57",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.12,
        "t.value": -5.05,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 7,
        "i %": 3.1,
        "sample": 226,
        "% af samlet befolkning": 1.18,
        "Antal ensomme": 2138,
        "pointLoss": "93.497.66 kr.",
        "pointGain": "199.935.958 kr."
    },
    {
        "id": "UCLA151",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.06,
        "t.value": -10.71,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 26,
        "i %": 6.28,
        "sample": 414,
        "% af samlet befolkning": 2.16,
        "Antal ensomme": 7943,
        "pointLoss": "93.553.59 kr.",
        "pointGain": "743.063.477 kr."
    },
    {
        "id": "UCLA160",
        "age": "All",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.06,
        "t.value": -10.7,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 31,
        "i %": 4.37,
        "sample": 709,
        "% af samlet befolkning": 3.71,
        "Antal ensomme": 9470,
        "pointLoss": "94.279.85 kr.",
        "pointGain": "892.838.092 kr."
    },
    {
        "id": "UCLA155",
        "age": "25 to 34",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.62,
        "Std..Error": 0.03,
        "t.value": -21.09,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 174,
        "i %": 10.15,
        "sample": 1715,
        "% af samlet befolkning": 8.97,
        "Antal ensomme": 53155,
        "pointLoss": "94.603.52 kr.",
        "pointGain": "5.028.617.904 kr."
    },
    {
        "id": "UCLA20",
        "age": "75 og derover",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.5,
        "Std..Error": 0.1,
        "t.value": -4.96,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 17,
        "i %": 6.83,
        "sample": 249,
        "% af samlet befolkning": 1.3,
        "Antal ensomme": 5193,
        "pointLoss": "73.268.27 kr.",
        "pointGain": "380.502.045 kr."
    },
    {
        "id": "UCLA102",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.63,
        "Std..Error": 0.04,
        "t.value": -16.96,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 82,
        "i %": 5.33,
        "sample": 1538,
        "% af samlet befolkning": 8.04,
        "Antal ensomme": 25050,
        "pointLoss": "96.019.00 kr.",
        "pointGain": "2.405.266.118 kr."
    },
    {
        "id": "UCLA60",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.63,
        "Std..Error": 0.31,
        "t.value": -2.01,
        "Pr...t..": 0.06,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 8.33,
        "sample": 24,
        "% af samlet befolkning": 0.13,
        "Antal ensomme": 611,
        "pointLoss": "96.214.66 kr.",
        "pointGain": "58.784.571 kr."
    },
    {
        "id": "UCLA107",
        "age": "45 to 54",
        "sex": "Both",
        "education": "All",
        "wellbeingCoefficient": -0.63,
        "Std..Error": 0.02,
        "t.value": -26.37,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 228,
        "i %": 6.29,
        "sample": 3625,
        "% af samlet befolkning": 18.95,
        "Antal ensomme": 69651,
        "pointLoss": "96.314.93 kr.",
        "pointGain": "6.708.424.821 kr."
    },
    {
        "id": "UCLA165",
        "age": "All",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.63,
        "Std..Error": 0.04,
        "t.value": -18.07,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 150,
        "i %": 8.72,
        "sample": 1721,
        "% af samlet befolkning": 9,
        "Antal ensomme": 45823,
        "pointLoss": "96.485.76 kr.",
        "pointGain": "4.421.265.667 kr."
    },
    {
        "id": "UCLA163",
        "age": "All",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.63,
        "Std..Error": 0.02,
        "t.value": -39.52,
        "Pr...t..": "1,15776607310891e-314",
        "antal ensomme i sample (>6 på UCLA)": 509,
        "i %": 5.78,
        "sample": 8808,
        "% af samlet befolkning": 46.05,
        "Antal ensomme": 155493,
        "pointLoss": "96.704.82 kr.",
        "pointGain": "15.036.890.434 kr."
    },
    {
        "id": "UCLA111",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.48,
        "Std..Error": 0.12,
        "t.value": -3.94,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 7,
        "i %": 3.76,
        "sample": 186,
        "% af samlet befolkning": 0.97,
        "Antal ensomme": 2138,
        "pointLoss": "70.229.33 kr.",
        "pointGain": "150.178.822 kr."
    },
    {
        "id": "UCLA150",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.64,
        "Std..Error": 0.06,
        "t.value": -11.54,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 58,
        "i %": 11.76,
        "sample": 493,
        "% af samlet befolkning": 2.58,
        "Antal ensomme": 17718,
        "pointLoss": "97.407.18 kr.",
        "pointGain": "1.725.881.938 kr."
    },
    {
        "id": "UCLA67",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.64,
        "Std..Error": 0.04,
        "t.value": -17.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 90,
        "i %": 4.75,
        "sample": 1893,
        "% af samlet befolkning": 9.9,
        "Antal ensomme": 27494,
        "pointLoss": "98.214.05 kr.",
        "pointGain": "2.700.276.453 kr."
    },
    {
        "id": "UCLA115",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.64,
        "Std..Error": 0.04,
        "t.value": -15.13,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 75,
        "i %": 7.12,
        "sample": 1054,
        "% af samlet befolkning": 5.51,
        "Antal ensomme": 22911,
        "pointLoss": "98.288.04 kr.",
        "pointGain": "2.251.925.663 kr."
    },
    {
        "id": "UCLA77",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.64,
        "Std..Error": 0.06,
        "t.value": -11.44,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 58,
        "i %": 7.83,
        "sample": 741,
        "% af samlet befolkning": 3.87,
        "Antal ensomme": 17718,
        "pointLoss": "98.428.75 kr.",
        "pointGain": "1.743.982.313 kr."
    },
    {
        "id": "UCLA162",
        "age": "All",
        "sex": "Mand",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.64,
        "Std..Error": 0.09,
        "t.value": -7.21,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 21,
        "i %": 11.73,
        "sample": 179,
        "% af samlet befolkning": 0.94,
        "Antal ensomme": 6415,
        "pointLoss": "98.468.19 kr.",
        "pointGain": "631.694.885 kr."
    },
    {
        "id": "UCLA47",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.47,
        "Std..Error": 0.06,
        "t.value": -8.42,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 22,
        "i %": 3.09,
        "sample": 711,
        "% af samlet befolkning": 3.72,
        "Antal ensomme": 6721,
        "pointLoss": "69.282.87 kr.",
        "pointGain": "465.629.657 kr."
    },
    {
        "id": "UCLA10",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.65,
        "Std..Error": 0.24,
        "t.value": -2.72,
        "Pr...t..": 0.02,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 9.09,
        "sample": 11,
        "% af samlet befolkning": 0.06,
        "Antal ensomme": 305,
        "pointLoss": "99.529.28 kr.",
        "pointGain": "30.404.859 kr."
    },
    {
        "id": "UCLA33",
        "age": "75 og derover",
        "sex": "Both",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.65,
        "Std..Error": 0.06,
        "t.value": -11.22,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 30,
        "i %": 4.58,
        "sample": 655,
        "% af samlet befolkning": 3.42,
        "Antal ensomme": 9165,
        "pointLoss": "99.621.80 kr.",
        "pointGain": "912.993.646 kr."
    },
    {
        "id": "UCLA173",
        "age": "All",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.03,
        "t.value": -25.39,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 279,
        "i %": 8.58,
        "sample": 3251,
        "% af samlet befolkning": 17,
        "Antal ensomme": 85231,
        "pointLoss": "100.460.80 kr.",
        "pointGain": "8.562.349.149 kr."
    },
    {
        "id": "UCLA40",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.47,
        "Std..Error": 0.07,
        "t.value": -6.75,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 20,
        "i %": 2.37,
        "sample": 843,
        "% af samlet befolkning": 4.41,
        "Antal ensomme": 6110,
        "pointLoss": "68.600.35 kr.",
        "pointGain": "419.129.712 kr."
    },
    {
        "id": "UCLA18",
        "age": "16 to 24",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.08,
        "t.value": -7.9,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 25,
        "i %": 13.59,
        "sample": 184,
        "% af samlet befolkning": 0.96,
        "Antal ensomme": 7637,
        "pointLoss": "100.813.32 kr.",
        "pointGain": "769.927.888 kr."
    },
    {
        "id": "UCLA100",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.09,
        "t.value": -6.93,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 16,
        "i %": 13.22,
        "sample": 121,
        "% af samlet befolkning": 0.63,
        "Antal ensomme": 4888,
        "pointLoss": "100.894.90 kr.",
        "pointGain": "493.152.576 kr."
    },
    {
        "id": "UCLA89",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.46,
        "Std..Error": 0.14,
        "t.value": -3.3,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 10,
        "i %": 8.77,
        "sample": 114,
        "% af samlet befolkning": 0.6,
        "Antal ensomme": 3055,
        "pointLoss": "67.552.03 kr.",
        "pointGain": "206.362.385 kr."
    },
    {
        "id": "UCLA91",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.04,
        "t.value": -18.29,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 97,
        "i %": 6,
        "sample": 1616,
        "% af samlet befolkning": 8.45,
        "Antal ensomme": 29632,
        "pointLoss": "101.283.99 kr.",
        "pointGain": "3.001.267.180 kr."
    },
    {
        "id": "UCLA158",
        "age": "All",
        "sex": "Mand",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.03,
        "t.value": -24.5,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 150,
        "i %": 4.15,
        "sample": 3612,
        "% af samlet befolkning": 18.88,
        "Antal ensomme": 45823,
        "pointLoss": "101.730.59 kr.",
        "pointGain": "4.661.599.354 kr."
    },
    {
        "id": "UCLA112",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.66,
        "Std..Error": 0.19,
        "t.value": -3.55,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 4.35,
        "sample": 92,
        "% af samlet befolkning": 0.48,
        "Antal ensomme": 1222,
        "pointLoss": "101.763.55 kr.",
        "pointGain": "124.349.590 kr."
    },
    {
        "id": "UCLA43",
        "age": "65 to 74",
        "sex": "Mand",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.46,
        "Std..Error": 0.15,
        "t.value": -3.19,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 3.66,
        "sample": 164,
        "% af samlet befolkning": 0.86,
        "Antal ensomme": 1833,
        "pointLoss": "67.439.73 kr.",
        "pointGain": "123.611.589 kr."
    },
    {
        "id": "UCLA76",
        "age": "55 to 64",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.67,
        "Std..Error": 0.21,
        "t.value": -3.17,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 10,
        "sample": 50,
        "% af samlet befolkning": 0.26,
        "Antal ensomme": 1527,
        "pointLoss": "102.517.73 kr.",
        "pointGain": "156.588.940 kr."
    },
    {
        "id": "UCLA104",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.67,
        "Std..Error": 0.07,
        "t.value": -9.53,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 22,
        "i %": 5.37,
        "sample": 410,
        "% af samlet befolkning": 2.14,
        "Antal ensomme": 6721,
        "pointLoss": "103.492.62 kr.",
        "pointGain": "695.543.296 kr."
    },
    {
        "id": "UCLA149",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.68,
        "Std..Error": 0.12,
        "t.value": -5.81,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 19,
        "i %": 15.32,
        "sample": 124,
        "% af samlet befolkning": 0.65,
        "Antal ensomme": 5804,
        "pointLoss": "105.576.69 kr.",
        "pointGain": "612.792.926 kr."
    },
    {
        "id": "UCLA71",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.45,
        "Std..Error": 0.07,
        "t.value": -6.79,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 28,
        "i %": 4.69,
        "sample": 597,
        "% af samlet befolkning": 3.12,
        "Antal ensomme": 8554,
        "pointLoss": "65.507.72 kr.",
        "pointGain": "560.328.383 kr."
    },
    {
        "id": "UCLA84",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.69,
        "Std..Error": 0.17,
        "t.value": -4.07,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 7,
        "i %": 16.28,
        "sample": 43,
        "% af samlet befolkning": 0.22,
        "Antal ensomme": 2138,
        "pointLoss": "106.403.96 kr.",
        "pointGain": "227.534.852 kr."
    },
    {
        "id": "UCLA125",
        "age": "35 to 44",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.69,
        "Std..Error": 0.08,
        "t.value": -8.8,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 38,
        "i %": 18.1,
        "sample": 210,
        "% af samlet befolkning": 1.1,
        "Antal ensomme": 11608,
        "pointLoss": "106.425.06 kr.",
        "pointGain": "1.235.434.199 kr."
    },
    {
        "id": "UCLA178",
        "age": "All",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.69,
        "Std..Error": 0.06,
        "t.value": -12.42,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 56,
        "i %": 12.87,
        "sample": 435,
        "% af samlet befolkning": 2.27,
        "Antal ensomme": 17107,
        "pointLoss": "106.481.26 kr.",
        "pointGain": "1.821.601.210 kr."
    },
    {
        "id": "UCLA157",
        "age": "All",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.69,
        "Std..Error": 0.04,
        "t.value": -18.13,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 129,
        "i %": 8.43,
        "sample": 1530,
        "% af samlet befolkning": 8,
        "Antal ensomme": 39408,
        "pointLoss": "107.061.82 kr.",
        "pointGain": "4.219.067.175 kr."
    },
    {
        "id": "UCLA17",
        "age": "16 to 24",
        "sex": "Both",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.69,
        "Std..Error": 0.16,
        "t.value": -4.4,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 3,
        "i %": 11.54,
        "sample": 26,
        "% af samlet befolkning": 0.14,
        "Antal ensomme": 916,
        "pointLoss": "107.202.36 kr.",
        "pointGain": "98.246.640 kr."
    },
    {
        "id": "UCLA141",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.69,
        "Std..Error": 0.19,
        "t.value": -3.74,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 11,
        "i %": 18.64,
        "sample": 59,
        "% af samlet befolkning": 0.31,
        "Antal ensomme": 3360,
        "pointLoss": "107.510.98 kr.",
        "pointGain": "361.274.760 kr."
    },
    {
        "id": "UCLA139",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "All",
        "wellbeingCoefficient": -0.7,
        "Std..Error": 0.05,
        "t.value": -14.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 65,
        "i %": 9.33,
        "sample": 697,
        "% af samlet befolkning": 3.64,
        "Antal ensomme": 19857,
        "pointLoss": "107.881.73 kr.",
        "pointGain": "2.142.167.329 kr."
    },
    {
        "id": "UCLA70",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Erhvervsfaglig uddannelse",
        "wellbeingCoefficient": -0.44,
        "Std..Error": 0.06,
        "t.value": -7.94,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 43,
        "i %": 5.31,
        "sample": 810,
        "% af samlet befolkning": 4.23,
        "Antal ensomme": 13136,
        "pointLoss": "63.840.72 kr.",
        "pointGain": "838.606.796 kr."
    },
    {
        "id": "UCLA133",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.7,
        "Std..Error": 0.16,
        "t.value": -4.51,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 8,
        "i %": 12.31,
        "sample": 65,
        "% af samlet befolkning": 0.34,
        "Antal ensomme": 2444,
        "pointLoss": "108.578.53 kr.",
        "pointGain": "265.354.246 kr."
    },
    {
        "id": "UCLA116",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.43,
        "Std..Error": 0.12,
        "t.value": -3.54,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 16,
        "i %": 15.09,
        "sample": 106,
        "% af samlet befolkning": 0.55,
        "Antal ensomme": 4888,
        "pointLoss": "62.241.76 kr.",
        "pointGain": "304.224.352 kr."
    },
    {
        "id": "UCLA46",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.42,
        "Std..Error": 0.07,
        "t.value": -5.58,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 17,
        "i %": 3.41,
        "sample": 499,
        "% af samlet befolkning": 2.61,
        "Antal ensomme": 5193,
        "pointLoss": "59.733.82 kr.",
        "pointGain": "310.213.929 kr."
    },
    {
        "id": "UCLA136",
        "age": "25 to 34",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.71,
        "Std..Error": 0.16,
        "t.value": -4.47,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 1.82,
        "sample": 55,
        "% af samlet befolkning": 0.29,
        "Antal ensomme": 305,
        "pointLoss": "110.595.33 kr.",
        "pointGain": "33.785.387 kr."
    },
    {
        "id": "UCLA90",
        "age": "45 to 54",
        "sex": "Mand",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.71,
        "Std..Error": 0.18,
        "t.value": -3.93,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 13.79,
        "sample": 29,
        "% af samlet befolkning": 0.15,
        "Antal ensomme": 1222,
        "pointLoss": "111.118.50 kr.",
        "pointGain": "135.780.839 kr."
    },
    {
        "id": "UCLA101",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.72,
        "Std..Error": 0.07,
        "t.value": -10.17,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 43,
        "i %": 9.15,
        "sample": 470,
        "% af samlet befolkning": 2.46,
        "Antal ensomme": 13136,
        "pointLoss": "112.507.71 kr.",
        "pointGain": "1.477.892.577 kr."
    },
    {
        "id": "UCLA170",
        "age": "All",
        "sex": "Kvinde",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.72,
        "Std..Error": 0.07,
        "t.value": -10.26,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 35,
        "i %": 13.67,
        "sample": 256,
        "% af samlet befolkning": 1.34,
        "Antal ensomme": 10692,
        "pointLoss": "113.110.32 kr.",
        "pointGain": "1.209.378.939 kr."
    },
    {
        "id": "UCLA73",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.72,
        "Std..Error": 0.2,
        "t.value": -3.58,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 1.43,
        "sample": 70,
        "% af samlet befolkning": 0.37,
        "Antal ensomme": 305,
        "pointLoss": "113.255.06 kr.",
        "pointGain": "34.597.898 kr."
    },
    {
        "id": "UCLA68",
        "age": "55 to 64",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.73,
        "Std..Error": 0.3,
        "t.value": -2.46,
        "Pr...t..": 0.02,
        "antal ensomme i sample (>6 på UCLA)": 3,
        "i %": 11.54,
        "sample": 26,
        "% af samlet befolkning": 0.14,
        "Antal ensomme": 916,
        "pointLoss": "114.836.51 kr.",
        "pointGain": "105.243.031 kr."
    },
    {
        "id": "UCLA97",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.41,
        "Std..Error": 0.15,
        "t.value": -2.7,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 3.79,
        "sample": 132,
        "% af samlet befolkning": 0.69,
        "Antal ensomme": 1527,
        "pointLoss": "58.721.68 kr.",
        "pointGain": "89.693.426 kr."
    },
    {
        "id": "UCLA49",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.39,
        "Std..Error": 0.18,
        "t.value": -2.2,
        "Pr...t..": 0.03,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 1.79,
        "sample": 112,
        "% af samlet befolkning": 0.59,
        "Antal ensomme": 611,
        "pointLoss": "55.202.06 kr.",
        "pointGain": "33.726.978 kr."
    },
    {
        "id": "UCLA3",
        "age": "16 to 24",
        "sex": "Mand",
        "education": "Kort videregående uddannelse",
        "wellbeingCoefficient": -0.75,
        "Std..Error": 0.22,
        "t.value": -3.36,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 13.33,
        "sample": 15,
        "% af samlet befolkning": 0.08,
        "Antal ensomme": 611,
        "pointLoss": "118.716.35 kr.",
        "pointGain": "72.532.500 kr."
    },
    {
        "id": "UCLA28",
        "age": "75 og derover",
        "sex": "Kvinde",
        "education": "Mellemlang videregående uddannelse",
        "wellbeingCoefficient": -0.36,
        "Std..Error": 0.12,
        "t.value": -2.99,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 2,
        "i %": 1.19,
        "sample": 168,
        "% af samlet befolkning": 0.88,
        "Antal ensomme": 611,
        "pointLoss": "50.834.60 kr.",
        "pointGain": "31.058.576 kr."
    },
    {
        "id": "UCLA52",
        "age": "65 to 74",
        "sex": "Both",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.77,
        "Std..Error": 0.39,
        "t.value": -1.98,
        "Pr...t..": 0.06,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 3.57,
        "sample": 28,
        "% af samlet befolkning": 0.15,
        "Antal ensomme": 305,
        "pointLoss": "120.894.53 kr.",
        "pointGain": "36.931.656 kr."
    },
    {
        "id": "UCLA106",
        "age": "45 to 54",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.77,
        "Std..Error": 0.11,
        "t.value": -6.76,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 10,
        "i %": 13.51,
        "sample": 74,
        "% af samlet befolkning": 0.39,
        "Antal ensomme": 3055,
        "pointLoss": "121.229.51 kr.",
        "pointGain": "370.339.874 kr."
    },
    {
        "id": "UCLA121",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.31,
        "Std..Error": 0.12,
        "t.value": -2.66,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 4.72,
        "sample": 127,
        "% af samlet befolkning": 0.66,
        "Antal ensomme": 1833,
        "pointLoss": "44.047.30 kr.",
        "pointGain": "80.735.154 kr."
    },
    {
        "id": "UCLA154",
        "age": "25 to 34",
        "sex": "Both",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.79,
        "Std..Error": 0.17,
        "t.value": -4.69,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 10,
        "i %": 23.26,
        "sample": 43,
        "% af samlet befolkning": 0.22,
        "Antal ensomme": 3055,
        "pointLoss": "125.079.53 kr.",
        "pointGain": "382.101.153 kr."
    },
    {
        "id": "UCLA98",
        "age": "45 to 54",
        "sex": "Kvinde",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.79,
        "Std..Error": 0.14,
        "t.value": -5.61,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 6,
        "i %": 13.33,
        "sample": 45,
        "% af samlet befolkning": 0.24,
        "Antal ensomme": 1833,
        "pointLoss": "126.479.38 kr.",
        "pointGain": "231.826.503 kr."
    },
    {
        "id": "UCLA108",
        "age": "35 to 44",
        "sex": "Mand",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -0.8,
        "Std..Error": 0.19,
        "t.value": -4.31,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 5,
        "i %": 8.93,
        "sample": 56,
        "% af samlet befolkning": 0.29,
        "Antal ensomme": 1527,
        "pointLoss": "127.349.53 kr.",
        "pointGain": "194.517.848 kr."
    },
    {
        "id": "UCLA117",
        "age": "35 to 44",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.8,
        "Std..Error": 0.12,
        "t.value": -6.95,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 15,
        "i %": 15.63,
        "sample": 96,
        "% af samlet befolkning": 0.5,
        "Antal ensomme": 4582,
        "pointLoss": "128.323.71 kr.",
        "pointGain": "588.017.542 kr."
    },
    {
        "id": "UCLA1",
        "age": "16 to 24",
        "sex": "Mand",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.83,
        "Std..Error": 0.15,
        "t.value": -5.49,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 9,
        "i %": 18.37,
        "sample": 49,
        "% af samlet befolkning": 0.26,
        "Antal ensomme": 2749,
        "pointLoss": "132.860.43 kr.",
        "pointGain": "365.283.695 kr."
    },
    {
        "id": "UCLA66",
        "age": "55 to 64",
        "sex": "Mand",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -0.84,
        "Std..Error": 0.21,
        "t.value": -4.03,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 3.33,
        "sample": 30,
        "% af samlet befolkning": 0.16,
        "Antal ensomme": 305,
        "pointLoss": "135.575.99 kr.",
        "pointGain": "41.416.643 kr."
    },
    {
        "id": "UCLA7",
        "age": "16 to 24",
        "sex": "Kvinde",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.85,
        "Std..Error": 0.14,
        "t.value": -5.98,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 16,
        "i %": 36.36,
        "sample": 44,
        "% af samlet befolkning": 0.23,
        "Antal ensomme": 4888,
        "pointLoss": "138.267.83 kr.",
        "pointGain": "675.823.443 kr."
    },
    {
        "id": "UCLA14",
        "age": "16 to 24",
        "sex": "Both",
        "education": "Grundskole",
        "wellbeingCoefficient": -0.86,
        "Std..Error": 0.1,
        "t.value": -8.53,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 25,
        "i %": 26.88,
        "sample": 93,
        "% af samlet befolkning": 0.49,
        "Antal ensomme": 7637,
        "pointLoss": "139.674.10 kr.",
        "pointGain": "1.066.714.006 kr."
    },
    {
        "id": "UCLA50",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "Lang videregående uddannelse",
        "wellbeingCoefficient": -0.99,
        "Std..Error": 0.22,
        "t.value": -4.48,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 1.61,
        "sample": 62,
        "% af samlet befolkning": 0.32,
        "Antal ensomme": 305,
        "pointLoss": "166.627.44 kr.",
        "pointGain": "50.902.445 kr."
    },
    {
        "id": "UCLA146",
        "age": "25 to 34",
        "sex": "Kvinde",
        "education": "Gymnasiel uddannelse",
        "wellbeingCoefficient": -1.04,
        "Std..Error": 0.24,
        "t.value": -4.27,
        "Pr...t..": 0,
        "antal ensomme i sample (>6 på UCLA)": 4,
        "i %": 19.05,
        "sample": 21,
        "% af samlet befolkning": 0.11,
        "Antal ensomme": 1222,
        "pointLoss": "177.186.59 kr.",
        "pointGain": "216.512.493 kr."
    },
    {
        "id": "UCLA45",
        "age": "65 to 74",
        "sex": "Kvinde",
        "education": "Under uddannelse",
        "wellbeingCoefficient": -1.3,
        "Std..Error": 0.4,
        "t.value": -3.28,
        "Pr...t..": 0.01,
        "antal ensomme i sample (>6 på UCLA)": 1,
        "i %": 7.69,
        "sample": 13,
        "% af samlet befolkning": 0.07,
        "Antal ensomme": 305,
        "pointLoss": "238.007.70 kr.",
        "pointGain": "72.708.155 kr."
    }
]